### ISSUE TITLE
Вложенные списки

### ISSUE THREAD

**Issue by iamstarkov** [FrontenderMagazine/chrome-developer-tools#2]
Нужно решить что-то с вложенными списками:
![](http://content.screencast.com/users/yaajing/folders/Jing/media/0df8185d-c05d-4aa9-9bf5-1862804148be/00000048.png)

**Comment by SilentImp** [comment]
почему? я вообще то делал этот отступ осознанно.
что бы разделить визуально кирпич списка.

**Comment by iamstarkov** [comment]
Мне ближе формат, при котором ToC идёт одним монолитным блоком:
![](http://content.screencast.com/users/yaajing/folders/Jing/media/55933ab9-ff53-4de6-ad32-d54665616e43/00000051.png)

**Comment by iamstarkov** [comment]
`¯\_(ツ)_/¯`
