### ISSUE TITLE
таблица содержимого

### ISSUE THREAD

**Issue by iamstarkov** [FrontenderMagazine/chrome-developer-tools#3]
Нужно определиться каким механизмом мы всё таки пользуемся или пустыми ссылками в заголовках с кастомными якорями, или опираемся на текущую реализацию якорной навигации (транслитерации заголовков)

**Comment by SilentImp** [comment]
тот же механизм, который использовали в статье Игоря или Наташи

**Comment by iamstarkov** [comment]
пока ни в одной из опубликованных статей не было ToC

**Comment by SilentImp** [comment]
В самих статьях были. Убрали на стадии релиза.

**Comment by iamstarkov** [comment]
`¯\_(ツ)_/¯`
