### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by dandv** [FrontenderMagazine/chrome-developer-tools#7]

**Comment by iamstarkov** [comment]
what do you mean?

**Comment by iamstarkov** [comment]
it is the translation in Russian of the https://developer.chrome.com/devtools/docs/console documentation. supposed to be published here https://frontender.info/chrome-developer-tools/. but somehow its not found /cc @SilentImp

**Comment by SilentImp** [comment]
Yay! I think it's a site rebuild problem. Will fix later today.

**Comment by SilentImp** [comment]
fixed
